name: Continuous Integration

on:
  push:
    branches:
    - "*"
  pull_request:
    branches: [ main ]

jobs:

  Rules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run tests for rules
      run: ./scripts/run-policy-tests.sh

    - name: Download latest modelsource
      run: |
        LATEST_VERSION=$(curl -s https://api.github.com/repos/mxlint/mxlint-cli/releases/latest | grep "tag_name" | cut -d '"' -f 4)
        curl -L https://github.com/mxlint/mxlint-cli/archive/refs/tags/${LATEST_VERSION}.zip -o modelsource.zip
        unzip modelsource.zip 
        mv mxlint-cli-*/resources/modelsource-v1 modelsource
        rm modelsource.zip
        rm -rf mxlint-cli-*

    - name: Lint report
      run: |
        mkdir -p .ci
        cat > .ci/lint.yaml << 'EOF'
        rules:
          path: ./rules
        modelsource: ./modelsource
        lint:
          xunitReport: report.xml
          jsonFile: report.json
        EOF
        ./bin/mxlint --config .ci/lint.yaml lint

    - name: Check XML output
      run: |
        [ -f report.xml ] && cat report.xml || echo "report.xml was not generated"

    - name: Check JSON output
      run: |
        [ -f report.json ] && cat report.json || echo "report.json was not generated"

    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: report
        path: report.*
