name: Release

on:
  release:
    types: [created]

jobs:
  release-rules:
    name: Release rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip rules directory
        run: zip -r rules.zip rules/ -x '*_test.rego' -x '*_test.yaml'

      - name: Create Tar.gz of rules directory
        run: tar -czvf rules.tar.gz --exclude='*_test.rego' --exclude='*_test.yaml' rules/

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Upload Release Asset (ZIP)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./rules.zip
          asset_name: rules-${{ steps.get_release.outputs.tag_name}}.zip
          asset_content_type: application/zip

      - name: Upload Release Asset (tar.gz)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./rules.tar.gz
          asset_name: rules-${{ steps.get_release.outputs.tag_name}}.tar.gz
          asset_content_type: application/gzip